syntax on
set number
set hlsearch
set termguicolors

let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_theme='wal'
let g:airline#extensions#branch#enabled=1

inoremap <C-c> <Esc>

